export const GET_LOCATION_WEATHER_REQUEST = "GET_LOCATION_WEATHER_REQUEST";
// export const GET_CITY_KEY = "GET_CITY_KEY";
// export const GET_CITY_CURRENT_WEATHER = "GET_CITY_CURRENT_WEATHER";
export const ADD_FIVEDAYSFORECAST = "ADD_FIVEDAYSFORECAST";
export const ADD_FAVORITE_LOCATION = "ADD_FAVORITE_LOCATION";
export const REMOVE_FAVORITE_LOCATION = "REMOVE_FAVORITE_LOCATION";
